### ISSUE TITLE
not working on Windows

### ISSUE THREAD

**Issue by kiddliu** [lee5i3/audit-check#14]
## Expected Behavior
audit-check works on Windows

## Actual Behavior
Error: spawn npm ENOENT

## Steps to Reproduce the Problem

  1. Install via `npm i -D audit-check`
  2. Run via `npx audit-check`

## Specifications

  - Version: 1.0.3
  - Platform: Windows
  - Subsystem: node v13.12.0 npm v6.14.4

## Note

https://github.com/lee5i3/audit-check/blob/a7d7da6bc3a10d912fe9199a105b807885f3a9d1/bin/index.js#L17

Check the platform to provide the correct NPM command

```js
/^win/.test(process.platform) ? 'npm.cmd' : 'npm'
```

**Comment by lee5i3** [comment]
Thanks, I'll look into this
